### ISSUE TITLE
Remove cap12s.fact from this role?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-bootstrap#7]
Now included in debops.core …

https://github.com/debops/ansible-bootstrap/tree/master/files/etc/ansible/facts.d
https://github.com/debops/ansible-core/tree/master/files/etc/ansible/facts.d

**Comment by drybjed** [comment]
`debops.bootstrap` uses `cap12s` fact to check if [hostname can be changed](https://github.com/debops/ansible-bootstrap/blob/master/tasks/main.yml#L170-L184) which might not be possible in restricted containers. Because `debops.core` might not have been run at this time, this fact needs to be available in this role as well.

**Comment by ypid** [comment]
Right, sorry for that. I guess the other way around also makes no sense …
